export const LoginUser = 'login_user'
export const Errors = 'errors'
export const SendProductGetRequest = 'send_product_get_request'
export const GetProductRequestSuccess = 'get_product_request_success'
export const GetProductRequestFail = 'get_product_request_fail'
export const GetCustomerDetails = 'get_customer_details'
export const GetCartItems = 'get_cart_items'
export const AddCartItem = 'add_cart_item'
export const SetCartMessage = 'add_cart_error_message'

